# ExploitFixer by LinsaFTW
# Please help by donating, we require funds to continue with the development.
# https://paypal.me/LinsaFTW
#

# WARNING: Only NullAddress, UUIDSpoof, CustomPayload and Commands modules work on BungeeCord.
# This is because the other modules cant do anything on BungeeCord.
# The other modules require ExploitFixer to be installed in Spigot with ProtocolLib.
# You need to install the plugin on BungeeCord and all Spigot servers.
#

# Checks works with VLs, this a counter to execute different commands on
# different levels of violations to allow customization of the modules.
#

# Shows notifications to console and players with permissions.
notifications:
  enabled: true

  # Placeholders: %player% %ping% %check% %vls%
  message: "&c&lEF: &e%player% &7(&a%ping%ms&7) &ffailed &6%check% &7(&c%vls% vls&7)"

# Prevents a variety of exploits that occur on connection establish.
# Players wont be able to type messages/commands until the connection is secured. (You wont notice this)
connection:
  # Prevents null addresses from fake Bungee IP Forwarding to bypass IP Whitelist.
  # NullAddress only affects non-firewalled servers using IP Whitelist.
  nulladdress: true

  # Prevents changing UUIDs with spoofed BungeeCord IP Forwarding.
  # UUIDSpoof only affects non-firewalled servers with BungeeCord: true.
  uuidspoof: true

# Fixes items to remove invalid tags, enchants, effects, etc...
itemsfix:
  enabled: true

  # Maximum stack size obtainable with creative packets. (Set to 0 to allow everything)
  max_stack_size: 64

  # Maximum enchant level obtainable with creative packets. (Set to 0 to remove all enchants, -1 to disable)
  enchant_limit: 10

# Prevents the use of CustomPayload packets to exploit the server.
custompayload:
  enabled: true

  # Blocks different types of invalid packets.
  invalid:
    # Limits the amount of channels registered per player.
    max_channels:
      # Vls to add when max channels are exceed. (Set to 0 to disable)
      vls: 1000

      # Maximum amounts of channels allowed per player.
      amount: 512

    # Never disable this and instead increase max_bytes if you have false positives.
    big_data:
      # Vls to add when too big packets are sent. (Set to 0 to disable)
      vls: 1000

      # Maximum amount of bytes per packet.
      max_bytes: 16000

    # Checks CustomPayload books for invalid data.
    books:
      # Vls to add when too big packets are sent. (Set to 0 to disable)
      vls: 1000

      # Maximum amount of bytes per page.
      max_bytes: 258

  # Amount of violations required to cancel.
  cancel_vls: 400

  # Amount of violations to reduce per second.
  reduce_vls: 400

  # When a valid packet is sent the following amount of vls will be applied.
  multipliers:
    OTHER: 0.1
    SETTINGS: 0.5
    MC|BSign: 50
    MC|BEdit: 50
    MC|BOpen: 50

  # Placeholders: %player%
  # Commands to execute when a players reachs a violation level.
  violations:
    400:
      - "notification"
    600:
      - "notification"
      - "kick"

# Prevents the use of packets to exploit the server.
# This prevents almost every exploit available for Bukkit.
packets:
  enabled: true

  # Amount of vls required to start cancelling packets.
  cancel_vls: 500

  # Amount of vls to reduce per second.
  reduce_vls: 300

  # Blocks packets when they arent meant to be sent or if they sent invalid data.
  invalid:
    # Cancells packets if the player sending them is offline.
    offline: true

    # Never disable this and instead increase max_bytes if you have false positives.
    # This will check if integers, floats, doubles and packets have a invalid size.
    big_data:
      # Vls to add when too big packets are sent. (Set to -1 to disable)
      vls: 1000

      # Maximum amount of bytes allowed per packet. (Increase to 80000 to allow Shulker Box)
      max_bytes: 20000

      # Maximum amount of bytes allowed per book page.
      max_bytes_book: 268

      # Maximum amount of bytes allowed per sign line.
      max_bytes_sign: 47

    # Checks if players send WINDOW_CLICK packets with another item in cursor. (Set to -1 to disable)
    window_click: 1000

    # Checks if players send BLOCK_PLACE packets with another item in hand. (Set to -1 to disable)
    block_place: 1000

    # Checks if players send BLOCK_DIG packets with another item in hand. (Set to -1 to disable)
    block_dig: 1000

    # Checks if players send SET_CREATIVE_SLOT packets without creative. (Set to -1 to disable)
    set_creative_slot: 1000

  # When a valid packet is sent the following amount of vls will be applied to the player.
  # This is made to prevent packet spamming.
  multipliers:
    ABILITIES: 1
    ARM_ANIMATION: 3
    BLOCK_DIG: 3
    BLOCK_PLACE: 4.25
    CUSTOM_PAYLOAD: 0.1
    ENTITY_ACTION: 4
    FLYING: 0.5
    LOOK: 0.75
    POSITION_LOOK: 0.75
    POSITION: 3.5
    SET_CREATIVE_SLOT: 0.5
    SETTINGS: 0.5
    TAB_COMPLETE: 2
    UPDATE_SIGN: 90
    USE_ENTITY: 4
    USE_ITEM: 4
    WINDOW_CLICK: 5

  # Placeholders: %player%
  # Commands to execute when a players reachs a violation level.
  violations:
    500:
      - "notification"
    1000:
      - "notification"
      - "kick"

# Checks if players try to crash/exploit the server with commands.
commands:
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 0

  # Commands to detect.
  commands:
    - "//calc"
    - "//calculate"
    - "//eval"
    - "//evaluate"
    - "//solve"
    - "/hd readtext"
    - "/holo readtext"
    - "/hologram readtext"
    - "/holograms readtext"
    - "/holographicdisplays readtext"
    - "/pex promote"
    - "/pex demote"
    - "/promote"
    - "/demote"
    - "/execute"

  # Placeholders: %player%
  violations:
    1:
      - "notification"
      - "kick"
