# Shows notifications on detection.
notifications:
  # Do you want to enable notifications?
  enabled: true

  # Placeholders: %player% %ping%
  # %check% gets replaced dynamically by the check.
  message: "&c&lEF: &e%player% &f| &6%check% &f| &c%ping%ms"

# Prevents exploits with custompayload packets.
custompayload:
  # Do you want to enable this module?
  enabled: true

  # Kick the player on detection?
  # Set to false to only cancel.
  kick: true

  # Maximum custom payload packets that can be sent per second.
  limit:
    normal: 6
    # Increase if you have false positives in BungeeCord.
    other: 400

  # Cancells invalid block_place packets with books.
  block_place: true

  # Placeholders: %player%
  punish_commands:
    - ""

# Checks if players have a invalid UUID.
uuidspoof:
  # Do you want to enable this module?
  enabled: true

  # Placeholders: %player%
  punish_commands:
    - ""

# Checks if players try to crash/exploit the server with commands.
commands:
  # Do you want to enable this module?
  enabled: true

  # Kick the player on detection?
  # Set to false to only cancel.
  kick: false

  # Commands to detect.
  commands:
    - "//calc"
    - "//calculate"
    - "//eval"
    - "//evaluate"
    - "//solve"
    - "/hd readtext"
    - "/holographicdisplays readtext"
    - "/pex promote"
    - "/pex demote"
    - "/promote"
    - "/demote"

  # Placeholders: %player%
  punish_commands:
    - ""

##############################
#         Bukkit only        #
##############################

# Limits packets with ProtocolLib to avoid exploits.
packets:
  # Do you want to enable this module?
  enabled: true

  # Max packets per second.
  limits:
    INTERACT: 80
    INTERACT_BOOKS: 5
    ABILITIES: 250
    ARM_ANIMATION: 80
    BLOCK_DIG: 120
    BLOCK_PLACE: 80
    KEEP_ALIVE: 5
    POSITION: 250
    USE_ENTITY: 80
    USE_ITEM: 80
    WINDOW_CLICK: 80

# Prevents duplication with Signs/Books.
duplication:
  # Do you want to enable this module?
  enabled: true

  # Kick the player on detection? If you dont it will only cancel.
  kick: false

  # Placeholders: %player%
  punish_commands:
    - ""

# Prevents exploits with various inventory exploits. (Prevents hacked creative items)
inventory:
  # Do you want to enable this module?
  enabled: true

  # Kick the player on detection? If you dont it will only cancel.
  kick: false

  # Cancells invalid window_click packets involving inventory slots.
  window_click: false

  # Placeholders: %player%
  punish_commands:
    - ""