# Shows notifications on detection.
notifications:
  # Do you want to enable notifications?
  enabled: true

  # Placeholders: %player% %ping%
  # %check% gets replaced dynamically by the check.
  message: "&c&lEF: &e%player% &f| &6%check% &f| &c%ping%ms"

# Checks if players have a invalid UUID.
uuidspoof:
  # Do you want to enable this module?
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 1

  # Placeholders: %player%
  thresholds:
    1:
      - "kick"
      - "notification"

# Limits custom_payload packets to avoid exploits.
custompayload:
  # Do you want to enable this module?
  enabled: true

  # Max amount of registered channels per player allowed.
  max_channels: 256

  # Amount of violations required to cancel.
  cancel_vls: 400

  # Amount of violations to reduce per second.
  reduce_vls: 500

  multipliers:
    OTHER: 1.25
    MAX_CHANNELS: 600
    MC|BSign: 50
    MC|BEdit: 50
    MC|BOpen: 50

  # Placeholders: %player%
  thresholds:
    600:
      - "kick"
      - "notification"

# Cancels common kinds of invalid packets and limits valid packets.
packets:
  # Do you want to enable this module?
  enabled: true

  # Cancells packets with big data length.
  big_data: true

  # Cancells packets from offline players.
  offline: true

  # Cancells invalid window_click packets.
  window_click: true

  # Cancells invalid block_place packets.
  block_place: true

  # Cancells invalid block_dig packets.
  block_dig: true

  # Cancells invalid set_creative_slot packets.
  set_creative_slot: true

  # Amount of violations required to cancel.
  cancel_vls: 200

  # Amount of violations to reduce per second.
  reduce_vls: 600

  # When a valid packet is sent the following amount of violations will be applied.
  multipliers:
    ABILITIES: 1
    ARM_ANIMATION: 4
    BLOCK_DIG: 4
    BLOCK_PLACE: 4
    BLOCK_PLACE_BOOKS: 50
    ENTITY_ACTION: 4
    POSITION: 0.8
    SET_CREATIVE_SLOT: 1
    TAB_COMPLETE: 8
    UPDATE_SIGN: 95
    USE_ENTITY: 4
    USE_ITEM: 4
    WINDOW_CLICK: 4

  # Placeholders: %player%
  thresholds:
    200:
      - "notification"
    2500:
      - "kick"
      - "notification"

# Checks if players try to crash/exploit the server with commands.
commands:
  # Do you want to enable this module?
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 1

  # Commands to detect.
  commands:
    - "//calc"
    - "//calculate"
    - "//eval"
    - "//evaluate"
    - "//solve"
    - "/hd readtext"
    - "/holographicdisplays readtext"
    - "/pex promote"
    - "/pex demote"
    - "/promote"
    - "/demote"
    - "/execute"

  # Placeholders: %player%
  thresholds:
    2:
      - "kick"
      - "notification"

# Recreates items obtained in creative to remove invalid tags, enchants, etc.
itemsfix:
  # Do you want to enable this module?
  enabled: true

# Prevents invalid book creation.
books:
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 1

  # Placeholders: %player%
  thresholds:
    2:
      - "kick"
      - "notification"

# Prevents invalid sign creation.
signs:
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 1

  # Placeholders: %player%
  thresholds:
    2:
      - "kick"
      - "notification"

# Prevents duplication with Signs/Books by cancelling characters of 3 or more bytes long.
duplication:
  # Do you want to enable this module?
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 1

  # Maximum bytes allowed per character.
  # Common keyboard characters are 1 byte long.
  # Characters with tildes are 2 bytes long.
  # Chinese characters are 3 bytes long.
  # Emojis are 4 bytes long.
  max_bytes: 2

  # Placeholders: %player%
  thresholds:
    2:
      - "kick"
      - "notification"