# ExploitFixer developed by LinsaFTW.
#
# WARNING: Only NullAddress, UUIDSpoof, CustomPayload and Commands check works on BungeeCord.
# The other checks require to be installed in Spigot with ProtocolLib.
# It is recommended to install the plugin on BungeeCord and all Spigot servers.
# The plugin will increase the performance by limiting and cancelling invalid packets.

notifications:
  enabled: true

  # Placeholders: %player% %ping% %check% %vls%
  message: "&c&lEF: &e%player% &7(&a%ping%ms&7) &ffailed &6%check% &7(&c%vls% vls&7)"

# Prevents null addresses from fake bungee IP-Forward to bypass IPWhitelist.
# WARNING: This is not a real fix, to fix this you need to host your network on a dedicated/vps machine
# and properly setup a firewall/airgap technique to prevent direct connections to your server.
# Follow this guide: https://www.spigotmc.org/wiki/firewall-guide/
nulladdress:
  enabled: true

# Checks if players have a invalid UUID. (Works with premium and no premium servers)
uuidspoof:
  # Do you want to enable this module?
  enabled: true

# Removes some ItemMeta from items to fix invalid tags, enchants, effects, etc...
itemsfix:
  enabled: true

  # Maximum enchant level obtainable with creative packets. (Set to 0 to disable custom enchants)
  enchant_limit: 0

# Limits custom_payload packets to avoid exploits.
custompayload:
  # Do you want to enable this module?
  enabled: true

  # Blocks different types of invalid packets.
  invalid:
    # Cancells packets with null/empty tags or content.
    empty: true

    # Limits the amount of channels registered per player.
    max_channels:
      # Vls to add when max channels are exceed. (Set to 0 to disable)
      vls: 1000

      # Maximum amounts of channels allowed per player.
      amount: 512

    # Never disable this and instead increase max_bytes if you have false positives.
    big_data:
      # Vls to add when too big packets are sent. (Set to 0 to disable)
      vls: 1000

      # Maximum amount of bytes per packet.
      max_bytes: 16000

  # Amount of violations required to cancel.
  cancel_vls: 400

  # Amount of violations to reduce per second.
  reduce_vls: 400

  multipliers:
    OTHER: 0.1
    MC|BSign: 50
    MC|BEdit: 50
    MC|BOpen: 50

  # Placeholders: %player%
  violations:
    400:
      - "notification"
    600:
      - "kick"
      - "notification"

packets:
  enabled: true

  # Amount of vls required to start cancelling packets.
  cancel_vls: 400

  # Amount of vls to reduce per second.
  reduce_vls: 300

  # Blocks different types of invalid packets.
  invalid:
    # Cancells packets if the player sending it is offline.
    offline: true

    # Never disable this and instead increase max_bytes if you have false positives.
    # This will check if integers, floats, doubles and packets have a invalid size.
    big_data:
      # Vls to add when too big packets are sent. (Set to 0 to disable)
      vls: 1000

      # Maximum amount of bytes per packet.
      max_bytes: 16000

      # Maximum amount of items per StructureModifier.
      max_structure: 25

    # big_data is required to enable this check. (Checks page quantity and bytes)
    books:
      vls:
        # Vls to add when invalid book packets are sent. (Set to 0 to disable)
        invalid: 1000

        # Vls to add when normal book packets are sent. (Set to 0 to disable)
        normal: 20

      # Maximum amount of bytes per page. (Prevents duplication and crashes)
      max_bytes: 256

    # Vls to add when invalid window_click packets are sent. (Set to 0 to disable)
    # Vls added by null InventoryView is the tenth part of the window_click vls.
    window_click: 1000

    # Vls to add when invalid block_place packets are sent. (Set to 0 to disable)
    block_place: 1000

    # Vls to add when invalid block_dig packets are sent. (Set to 0 to disable)
    block_dig: 1000

    # Vls to add when invalid set_creative_slot packets are sent. (Set to 0 to disable)
    set_creative_slot: 1000

  # When a valid packet is sent the following amount of vls will be applied.
  multipliers:
    ABILITIES: 1
    ARM_ANIMATION: 4.25
    BLOCK_DIG: 4.25
    BLOCK_PLACE: 4.25
    CUSTOM_PAYLOAD: 0.1
    ENTITY_ACTION: 4
    FLYING: 0.5
    LOOK: 0.75
    POSITION_LOOK: 0.75
    POSITION: 3.5
    SET_CREATIVE_SLOT: 0.5
    TAB_COMPLETE: 8
    UPDATE_SIGN: 90
    USE_ENTITY: 4
    USE_ITEM: 4
    WINDOW_CLICK: 5

  # Placeholders: %player%
  # Commands to execute when a players reachs a violation level.
  violations:
    500:
      - "notification"
    1000:
      - "kick"
      - "notification"

# Checks if players try to crash/exploit the server with commands.
commands:
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 0

  # Commands to detect.
  commands:
    - "//calc"
    - "//calculate"
    - "//eval"
    - "//evaluate"
    - "//solve"
    - "/hd readtext"
    - "/holographicdisplays readtext"
    - "/pex promote"
    - "/pex demote"
    - "/promote"
    - "/demote"
    - "/execute"

  # Placeholders: %player%
  violations:
    1:
      - "kick"
      - "notification"

# Prevents invalid sign creation.
signs:
  enabled: true

  # Amount of violations required to cancel.
  cancel_vls: 1

  # Amount of violations to reduce per second.
  reduce_vls: 0

  max_bytes: 34

  # Placeholders: %player%
  violations:
    1:
      - "kick"
      - "notification"