name: ExploitFixer
main: dev._2lstudios.exploitfixer.bukkit.ExploitFixer
version: 1.3.9
author: 2LS
api: "1.13"
api-version: "1.13"
softdepend: [HamsterAPI]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]
