name: ExploitFixer
main: twolovers.exploitfixer.bukkit.ExploitFixer
version: 1.1.4
author: 2LS
api-version: '1.13'
load: STARTUP
depend: [ProtocolLib]
loadbefore: [AAC, ViaVersion, ViaBackwards, ViaRewind, ViaPotions, ProtocolSupport]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]