name: ExploitFixer
main: twolovers.exploitfixer.bukkit.ExploitFixer
version: 1.2.4
author: 2LS
api: "1.13"
api-version: "1.13"
load: STARTUP
depend: [ProtocolLib]
loadbefore: [ProtocolLib, AAC, ViaVersion, ProtocolSupport]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]
