name: ExploitFixer
main: twolovers.exploitfixer.bukkit.ExploitFixer
version: 1.3.0
author: 2LS
api: "1.13"
api-version: "1.13"
soft-depend: [HamsterAPI]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]
