name: ExploitFixer
main: twolovers.exploitfixer.bukkit.ExploitFixer
version: 0.6.7
author: 2LS
softdepend: [ProtocolLib]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]