name: ExploitFixer
main: twolovers.exploitfixer.bukkit.ExploitFixer
version: 1.0.0
author: 2LS
api-version: '1.13'
softdepend: [ProtocolLib]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]